<a href="https://colab.research.google.com/github/jimmysoccer/test-only/blob/main/Reconstruction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use PCA matrix to reconstruct sequence 

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Load data

In [7]:
dat=np.load('/content/drive/MyDrive/DanWei/Copy of validate_array.npy')
dat.shape
# load pca 
with open("/content/drive/MyDrive/DanWei/Copy of normalize_pca.txt", "rb") as myFile:
    newdic= pickle.load(myFile)

print(newdic)
type(newdic)

{'A': [0.07525231330089575, 0.11110993247250554, 1.0, 0.10085171430385075, 0.3362586030378956, 0.08589557098930195, 0.3166716257763159, 0.07845695355133557, 0.29558950944630463, 0.0, 0.17264524667274148, 0.02519795885608285, 0.21399362066317887, 0.20352855444366297, 0.315091708147771], 'R': [1.0, 0.0, 0.4038784221987408, 0.5654030339035435, 0.19358241833934803, 0.9218071081013374, 0.706684933100523, 0.386763003529879, 0.4859773194257129, 0.35364725786412415, 0.853611611157344, 0.6896935049070329, 0.5301256891869882, 0.5887127624896037, 0.6865122676206136], 'N': [1.0, 0.33875792059923404, 0.08051659481278953, 0.5409271544498805, 0.17196565841462272, 0.08031021902130163, 0.18874324146258997, 0.5291298621814148, 0.3042291274231407, 0.46516048086757544, 0.3558216551514157, 0.38102091917816505, 0.07103751169386222, 0.0, 0.4581217601781321], 'D': [1.0, 0.25640988772162693, 0.32592183369372396, 0.4200305281353341, 0.5744582792254195, 0.1560420670881465, 0.0, 0.3091207506859722, 0.258039340323

dict

Calculate distance 

In [8]:
dat.shape

(29695, 19, 15)

In [58]:
#
sample=dat[:10000]
sample[1].shape

(19, 15)

In [12]:
len(sample)

100

In [13]:
seq=sample[1][0]
from scipy.spatial import distance
distance.euclidean(newdic['N'], seq)


1.6620416942409277

['A',
 'R',
 'N',
 'D',
 'C',
 'E',
 'Q',
 'G',
 'H',
 'I',
 'L',
 'K',
 'M',
 'F',
 'P',
 'S',
 'T',
 'W',
 'Y',
 'V']

In [14]:
from IPython.core.display import display_pretty
seq=sample[1][0]
from scipy.spatial import distance

def cal_distance(dict,seq):
  dist=[]
  index_code=list(dict.keys())

  seq_decode = ''
  for i in range(len(seq)):
    m1=seq[i] # each row w
    if max(m1) <= 0.1:
      continue 
    for key, value in dict.items():
      a1=dict[key]
      dist.append(distance.euclidean(dict[key], m1))

    seq_decode+=index_code[np.argmax(dist)]
  return seq_decode




In [15]:
sample[1][0]

array([0.00164328, 0.7478904 , 0.0805108 , 0.9984883 , 0.76167965,
       0.8150803 , 0.43347472, 0.16906214, 0.3319984 , 0.57055247,
       0.48174757, 0.3912905 , 0.43094915, 0.37598193, 0.34417993],
      dtype=float32)

In [129]:
def cal_distance(dict,seq):
  dist=[]
  index_code=list(dict.keys())
  
  for key, value in dict.items():
    a1=dict[key]
    dist.append(distance.euclidean(dict[key], seq))
  print(dist,'\n',index_code,'\n',np.argmin(dist))
  return index_code[np.argmin(dist)]

def code_seq(dict, mat):
  indexcode= ''

  for i in range(len(mat)):
    m1 = mat[i]
    value_max= np.max(m1)
    if value_max <= 0.1:
      continue
    indexcode+=cal_distance(newdic,m1)
  return indexcode

In [131]:
cal_distance(newdic,dat[18000][0])
time = 10
for i in range(time):
  cal_distance(newdic,dat[i][5])

[1.85370334786561, 1.6666525572729582, 1.662836896178565, 1.5814770610925557, 0.0047595317978336195, 1.6741205760114963, 1.590926860070447, 1.585363194859957, 1.4172159684554797, 1.566300915355485, 1.4514118611961344, 1.6909150732087401, 1.4811491631648064, 1.5775191302110223, 1.5559164191541495, 1.6617523601216615, 1.6374282030592051, 1.1433541579505537, 1.3029340883515557, 1.302050521437216] 
 ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'] 
 4
[1.2614838030130031, 1.1317111714867998, 0.9251964404796615, 0.7941558095948558, 1.27447917166706, 0.9848648353761443, 0.9732272276882438, 0.7572196641657346, 1.2043356673934278, 1.6710949017384442, 1.2734428464608605, 0.9811496718706995, 1.5907475041429087, 1.7292928112371164, 1.0028842637788427, 0.6554020027721255, 1.0174286870285827, 1.372798478535399, 1.2580049200603596, 1.329379302183149] 
 ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', '

In [147]:
time = 10
for i in range(time):
  cal_distance(newdic,dat[i+100][10])

[1.4292107651474688, 0.9965660003093266, 1.0603918520358175, 0.9091865306389169, 1.2053447689557202, 0.7998795553682074, 0.7342016955721102, 1.0988051570987163, 1.0672323677386213, 1.4576960356605124, 1.078947422320817, 0.8335451414535135, 1.3336088256198182, 1.4745838559783144, 0.9140390798967917, 0.9250025075752625, 1.1056734813282405, 1.1572842717783849, 1.0387986672669385, 1.1787882123057907] 
 ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V'] 
 6
[1.4291281924564636, 0.9984120242107714, 1.0572436855123903, 0.9058093774573901, 1.2062022613552599, 0.8002201724284717, 0.7350207970660669, 1.096052371654883, 1.0692143014456155, 1.460922564357144, 1.0825388003462313, 0.8356907411944707, 1.337131799712882, 1.477655124063498, 0.9138514129205111, 0.9213937899920277, 1.104188750985804, 1.158953792820846, 1.0396868915812059, 1.181945134504147] 
 ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', '

In [106]:
def reconstructSequence(dict,data):
  result = []
  for i in range(len(data)):
    currentSeq= ''
    dict_index=list(dict.keys())
    if(i%1000==0):
      print(str(i/len(data)*100)+'%')
    for j in range(len(data[i])):
      row = data[i][j]
      max_value= np.max(row)
      if max_value <= 0.1:
        continue
      #calculate distance
      dist = []
      for key, value in dict.items():
        dist.append(distance.euclidean(dict[key], row))
      currentSeq += dict_index[np.argmin(dist)]
    result.append(currentSeq)
  return result

In [95]:
def codeMat(data):
  result = []
  print('start codeMat processing')
  for i in range(len(data)):
    result.append(code_seq(newdic,data[i]))
    if(i%1000==0):
      print(str(i/len(data)*100)+'%')
  return result
  

In [ ]:
reconstructSequence(newdic,dat[:100])

In [140]:
def compare(dict,data,correct):
  result = []
  num = 0
  total = len(data)
  for i in range(len(data)):
    currentSeq= ''
    dict_index=list(dict.keys())
    if(i%1000==0):
      print(str(i/total*100)+'%')
    for j in range(len(data[i])):
      row = data[i][j]
      max_value= np.max(row)
      if max_value <= 0.1:
        continue
      #calculate distance
      dist = []
      for key, value in dict.items():
        dist.append(distance.euclidean(dict[key], row))
      currentSeq += dict_index[np.argmin(dist)]
    if(currentSeq==correct[j]):
      num += 1
  return num

In [146]:
compare(newdic,dat,correct_output)

0.0%
3.367570298029971%
6.735140596059942%
10.102710894089913%
13.470281192119884%
16.83785149014986%
20.205421788179827%
23.572992086209798%
26.94056238423977%
30.308132682269743%
33.67570298029972%
37.043273278329686%
40.41084357635965%
43.77841387438963%
47.145984172419595%
50.51355447044957%
53.88112476847954%
57.24869506650951%
60.61626536453949%
63.983835662569454%
67.35140596059944%
70.7189762586294%
74.08654655665937%
77.45411685468933%
80.8216871527193%
84.1892574507493%
87.55682774877926%
90.92439804680923%
94.29196834483919%
97.65953864286917%


0

In [17]:
seq1=sample[0][1]
seq1
#cal_distance(newdic,sample[0][1])

array([0.0932311 , 0.12475146, 0.9898873 , 0.11084824, 0.33429328,
       0.09250832, 0.31490415, 0.08610138, 0.30390126, 0.00269621,
       0.17761964, 0.02967362, 0.21799266, 0.20830743, 0.31666353],
      dtype=float32)

In [18]:
seq2=sample[11][1]
seq2

array([0.09028873, 0.12171932, 0.9898974 , 0.10715594, 0.33057198,
       0.09065212, 0.3131971 , 0.08410845, 0.3015342 , 0.00274389,
       0.17471546, 0.02940627, 0.21468134, 0.20447743, 0.31333315],
      dtype=float32)

In [19]:
print(cal_distance(newdic,seq1))
print(cal_distance(newdic,seq2))

A
A


In [77]:
code_seq(newdic,sample[0])


'CASSLSSSSSQQLYA'

In [ ]:
code_seq(newdic,sample[99])

C
A
S
S
L
S
S
S
S
S
Q
Q
L
Y
A


'CASSLSSSSSQQLYA'

In [ ]:
code_seq(newdic,sample[1])

C
A
S
S
L
S
S
S
S
S
Q
Q
L
Y
A


['C', 'A', 'S', 'S', 'L', 'S', 'S', 'S', 'S', 'S', 'Q', 'Q', 'L', 'Y', 'A']

In [ ]:
code_seq(newdic,sample[9])

['C', 'A', 'S', 'S', 'L', 'S', 'S', 'S', 'S', 'S', 'Q', 'Q', 'L', 'Y', 'A']

In [ ]:
code=[]
matrix=sample[1]

for i in range(len(matrix)):
  m1=matrix[i]
  code+=cal_distance(newdic,m1)

code

['A',
 'F',
 'F',
 'F',
 'A',
 'F',
 'F',
 'F',
 'F',
 'F',
 'F',
 'A',
 'A',
 'I',
 'I',
 'F',
 'F',
 'F',
 'F']

In [ ]:
seq=sample[1]
index_code=list(newdic.keys())
seq_decode = ''
dist=[]
maxcode=[]
for i in range(len(seq)):
  m1=seq[i] # each row w
  #if max(m1) <= 0.1:
   # continue 
  for key, value in newdic.items():
    a1=newdic[key]
    dist.append(distance.euclidean(newdic[key], m1))
\]
  #seq_decode=seq_decode+index_code[np.argmax(dist)]


IndexError: ignored

In [ ]:
maxcode

[0, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 313, 333, 353, 373]

In [ ]:
seq=sample[1]
len(seq)
#cal_distance(newdic,seq)
max(seq[1])


0.989408

In [ ]:
def seq_reconstruct(seq_array):
  for i in range(len(seq_array)):
    


In [145]:
my_file2 = open("/content/drive/MyDrive/DanWei/Copy of TumorCDR3.txt", "r")
content_list2 = my_file2.read().splitlines()

#content_list2=np.array(content_list2)

correct_output=[x for x in content_list2 if len(x)<=19]


In [111]:
temp_file = np.load('/content/drive/MyDrive/DanWei/Copy of validate_array.npy')
temp_file

array([[[0.00153992, 0.74626714, 0.08051175, ..., 0.429185  ,
         0.37619844, 0.34518185],
        [0.0932311 , 0.12475146, 0.9898873 , ..., 0.21799266,
         0.20830743, 0.31666353],
        [0.9666149 , 0.66482073, 0.41204515, ..., 0.2994463 ,
         0.28666407, 0.28645197],
        ...,
        [0.00153993, 0.00991142, 0.00747521, ..., 0.01008508,
         0.00809024, 0.00663861],
        [0.00125084, 0.00234121, 0.00226621, ..., 0.00251681,
         0.00206873, 0.00183993],
        [0.00136809, 0.00170216, 0.00128728, ..., 0.00166269,
         0.0012867 , 0.00146677]],

       [[0.00164328, 0.7478904 , 0.0805108 , ..., 0.43094915,
         0.37598193, 0.34417993],
        [0.09224171, 0.12319089, 0.989408  , ..., 0.21621484,
         0.20613731, 0.31471512],
        [0.9661741 , 0.6652579 , 0.41258848, ..., 0.2981643 ,
         0.2835009 , 0.2854536 ],
        ...,
        [0.00163864, 0.01050385, 0.00787834, ..., 0.01041115,
         0.0085658 , 0.00702032],
        [0.0